# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    working_directory: ~/django_playground
    docker:
      - image: circleci/python:3.6.8-jessie
        enviroment:
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.5.17-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            cd django_playground
            pip install -r requirements.txt
      - run:
          name: make migrations
          command: |
            . venv/bin/activate

            python manage.py makemigrations --settings django_playground.settings.ci
            python manage.py migrate --no-input --settings django_playground.settings.ci

      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate

            python manage.py test --settings django_playground.settings.ci
